In [1]:
import numpy as np
import pandas as pd

In [2]:
import os

In [3]:
os.getcwd()

'C:\\Users\\phani1'

In [4]:
users = pd.read_csv("Users.csv")

In [5]:
ratings = pd.read_csv("Ratings.csv")
books = pd.read_csv("Books.csv")

C:\Users\phani1\AppData\Local\Temp\ipykernel_4484\1722114352.py:2: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv("Books.csv")

In [6]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [7]:
books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            1
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [8]:
ratings.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [9]:
users.duplicated().sum()

0

# Popularity based recommender system!

formula: display 50 books with the highest average rating and only display books that have atleast 250 votes!

In [10]:
books.shape

(271360, 8)

In [11]:
print(books.shape)
print(users.shape)
print(ratings.shape)

(271360, 8)
(278858, 3)
(1149780, 3)

In [12]:
#merging two data frames

In [13]:
ratings

         User-ID         ISBN  Book-Rating
0         276725   034545104X            0
1         276726   0155061224            5
2         276727   0446520802            0
3         276729   052165615X            3
4         276729   0521795028            6
...          ...          ...          ...
1149775   276704   1563526298            9
1149776   276706   0679447156            0
1149777   276709   0515107662           10
1149778   276721   0590442449           10
1149779   276723  05162443314            8

[1149780 rows x 3 columns]

In [14]:
books

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...
...,...,...,...,...,...,...,...,...
271355,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm),http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...
271356,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...
271357,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...
271358,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...
271359,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...

In [15]:
#merge the two data frames on top of ISBN

In [16]:
ratings_with_name = ratings.merge(books,on="ISBN")

In [17]:
ratings_with_name.groupby("Book-Title").count()  #this juts sorted the books alphabetically so that all harry potter books come at one place (example).. we didnot groupby ISBN cause all harry potter books have random ISBN numbers.

,User-ID,ISBN,Book-Rating,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
Book-Title,,,,,,,,,
"A Light in the Storm: The Civil War Diary of Amelia Martin, Fenwick Island, Delaware, 1861 (Dear America)",4,4,4,4,4,4,4,4,4
Always Have Popsicles,1,1,1,1,1,1,1,1,1
Apple Magic (The Collector's series),1,1,1,1,1,1,1,1,1
"Ask Lily (Young Women of Faith: Lily Series, Book 5)",1,1,1,1,1,1,1,1,1
Beyond IBM: Leadership Marketing and Finance for the 1990s,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...
Ã?Â?lpiraten.,2,2,2,2,2,2,2,2,2
Ã?Â?rger mit Produkt X. Roman.,4,4,4,4,4,4,4,4,4
Ã?Â?sterlich leben.,1,1,1,1,1,1,1,1,1
Ã?Â?stlich der Berge.,3,3,3,3,3,3,3,3,3
Ã?Â?thique en toc,2,2,2,2,2,2,2,2,2

In [18]:
ratings_with_name.groupby("Book-Title").count()[['Book-Rating', 'User-ID']].reset_index()

,Book-Title,Book-Rating,User-ID
0,A Light in the Storm: The Civil War Diary of ...,4,4
1,Always Have Popsicles,1,1
2,Apple Magic (The Collector's series),1,1
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,1
4,Beyond IBM: Leadership Marketing and Finance ...,1,1
...,...,...,...
241066,Ã?Â?lpiraten.,2,2
241067,Ã?Â?rger mit Produkt X. Roman.,4,4
241068,Ã?Â?sterlich leben.,1,1
241069,Ã?Â?stlich der Berge.,3,3
241070,Ã?Â?thique en toc,2,2

In [19]:
##but we dont need user id 
##IMP!!! ---> Book rating is actually the number of ratings!

In [20]:
num_rating_df  = ratings_with_name.groupby('Book-Title').count()['Book-Rating'].reset_index()

In [21]:
#renaming a column!

In [22]:
num_rating_df.rename(columns={'Book-Rating' : 'number_of_ratings'}, inplace = True)

In [23]:
num_rating_df

                                               Book-Title  number_of_ratings
0        A Light in the Storm: The Civil War Diary of ...                  4
1                                   Always Have Popsicles                  1
2                    Apple Magic (The Collector's series)                  1
3        Ask Lily (Young Women of Faith: Lily Series, ...                  1
4        Beyond IBM: Leadership Marketing and Finance ...                  1
...                                                   ...                ...
241066                                      Ã?Â?lpiraten.                  2
241067                     Ã?Â?rger mit Produkt X. Roman.                  4
241068                                Ã?Â?sterlich leben.                  1
241069                              Ã?Â?stlich der Berge.                  3
241070                                  Ã?Â?thique en toc                  2

[241071 rows x 2 columns]

In [24]:
avg_rating_df = ratings_with_name.groupby("Book-Title").mean()['Book-Rating'].reset_index()

In [25]:
avg_rating_df.rename(columns = {"Book-Rating" : "Avg_rating"}, inplace= True);

In [26]:
avg_rating_df

                                               Book-Title  Avg_rating
0        A Light in the Storm: The Civil War Diary of ...    2.250000
1                                   Always Have Popsicles    0.000000
2                    Apple Magic (The Collector's series)    0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...    8.000000
4        Beyond IBM: Leadership Marketing and Finance ...    0.000000
...                                                   ...         ...
241066                                      Ã?Â?lpiraten.    0.000000
241067                     Ã?Â?rger mit Produkt X. Roman.    5.250000
241068                                Ã?Â?sterlich leben.    7.000000
241069                              Ã?Â?stlich der Berge.    2.666667
241070                                  Ã?Â?thique en toc    4.000000

[241071 rows x 2 columns]

In [27]:
z =avg_rating_df.merge(num_rating_df, on="Book-Title").reset_index()

In [28]:
z.iloc[4] #using iloc to find a specific book

index                                                                4
Book-Title            Beyond IBM: Leadership Marketing and Finance ...
Avg_rating                                                         0.0
number_of_ratings                                                    1
Name: 4, dtype: object

In [29]:
z.iloc[250]

index                                                              250
Book-Title           10-Minute Scrapbook Pages: Hundreds of Easy, I...
Avg_rating                                                         0.0
number_of_ratings                                                    1
Name: 250, dtype: object

In [30]:
z.drop('index', inplace = True, axis = 1) #removing a col

In [31]:
z

,Book-Title,Avg_rating,number_of_ratings
0,A Light in the Storm: The Civil War Diary of ...,2.250000,4
1,Always Have Popsicles,0.000000,1
2,Apple Magic (The Collector's series),0.000000,1
3,"Ask Lily (Young Women of Faith: Lily Series, ...",8.000000,1
4,Beyond IBM: Leadership Marketing and Finance ...,0.000000,1
...,...,...,...
241066,Ã?Â?lpiraten.,0.000000,2
241067,Ã?Â?rger mit Produkt X. Roman.,5.250000,4
241068,Ã?Â?sterlich leben.,7.000000,1
241069,Ã?Â?stlich der Berge.,2.666667,3
241070,Ã?Â?thique en toc,4.000000,2

In [32]:
popular_titles = z[z['number_of_ratings'] >=250]

In [33]:
popular_titles

,Book-Title,Avg_rating,number_of_ratings
764,1984,4.454225,284
818,1st to Die: A Novel,3.575639,509
1048,2nd Chance,3.269663,356
1760,A Bend in the Road,3.364162,346
2281,"A Child Called \It\"": One Child's Courage to S...",4.086792,265
...,...,...,...
233850,White Oleander : A Novel,3.506460,387
233851,White Oleander : A Novel (Oprah's Book Club),3.772472,356
234740,Wicked: The Life and Times of the Wicked Witch...,3.766871,326
234951,Wild Animus,1.019584,2502
240860,"\O\"" Is for Outlaw""",2.988848,269

In [34]:
##sorting in descending order
popular_df = popular_titles.sort_values("Avg_rating", ascending= False).head(50).reset_index()

In [35]:
popular_df

,index,Book-Title,Avg_rating,number_of_ratings
0,80434,Harry Potter and the Prisoner of Azkaban (Book 3),5.852804,428
1,80422,Harry Potter and the Goblet of Fire (Book 4),5.824289,387
2,80441,Harry Potter and the Sorcerer's Stone (Book 1),5.737410,278
3,80426,Harry Potter and the Order of the Phoenix (Boo...,5.501441,347
4,80414,Harry Potter and the Chamber of Secrets (Book 2),5.183453,556
5,191612,The Hobbit : The Enchanting Prelude to The Lor...,5.007117,281
6,187377,The Fellowship of the Ring (The Lord of the Ri...,4.948370,368
7,80445,Harry Potter and the Sorcerer's Stone (Harry P...,4.895652,575
8,211384,"The Two Towers (The Lord of the Rings, Part 2)",4.880769,260
9,219741,To Kill a Mockingbird,4.700000,510
10,183573,The Da Vinci Code,4.642539,898
11,187880,The Five People You Meet in Heaven,4.551163,430
12,180556,The Catcher in the Rye,4.545657,449
13,196326,The Lovely Bones: A Novel,4.468726,1295
14,764,1984,4.454225,284
15,144165,Prodigal Summer: A Novel,4.450593,253
16,128670,Neverwhere,4.449057,265
17,206502,The Secret Life of Bees,4.447028,774
18,168719,Stupid White Men ...and Other Sorry Excuses fo...,4.356890,283
19,223135,"Tuesdays with Morrie: An Old Man, a Young Man,...",4.354970,493
20,204387,The Red Tent (Bestselling Backlist),4.334716,723
21,191589,The Hitchhiker's Guide to the Galaxy,4.328358,268
22,129379,Nickel and Dimed: On (Not) Getting By in America,4.289552,335
23,93381,Into the Wild,4.273810,252
24,63867,Fahrenheit 451,4.264059,409
25,74750,Girl with a Pearl Earring,4.218631,526
26,136145,Outlander,4.173145,283
27,233370,Where the Heart Is (Oprah's Book Club (Paperba...,4.105983,585
28,156102,Seabiscuit: An American Legend,4.098182,275
29,107962,Life of Pi,4.088855,664
30,176845,The Bean Trees,4.087404,389
31,2281,"A Child Called \It\"": One Child's Courage to S...",4.086792,265
32,8434,ANGELA'S ASHES,4.075269,279
33,76343,Good in Bed,4.055102,490
34,64931,Fast Food Nation: The Dark Side of the All-Ame...,4.037383,321
35,12700,American Gods,4.006623,302
36,161645,Skipping Christmas,4.006211,322
37,105777,Left Behind: A Novel of the Earth's Last Days ...,4.003145,318
38,189551,"The Golden Compass (His Dark Materials, Book 1)",4.000000,336
39,181679,The Color Purple,3.964968,314
40,160336,Silence of the Lambs,3.960938,256
41,8752,About a Boy,3.900763,262
42,158138,Seven Up (A Stephanie Plum Novel),3.888489,278
43,175097,The Alchemist: A Fable About Following Your Dream,3.875940,266
44,80069,Hard Eight : A Stephanie Plum Novel (A Stephan...,3.825279,269
45,170101,Suzanne's Diary for Nicholas,3.820569,457
46,111073,Lord of the Flies,3.818533,259
47,5664,A Prayer for Owen Meany,3.796610,413
48,212070,"The Vampire Lestat (Vampire Chronicles, Book II)",3.777409,301
49,233851,White Oleander : A Novel (Oprah's Book Club),3.772472,356

In [36]:
df5 = popular_df.merge(books, on="Book-Title").drop_duplicates("Book-Title")[['Book-Title', 'Book-Author', 'Image-URL-M','number_of_ratings', 'Avg_rating']]

In [37]:
df6 = df5.reset_index().head(50)

In [50]:
df6

,index,Book-Title,Book-Author,Image-URL-M,number_of_ratings,Avg_rating
0,0,Harry Potter and the Prisoner of Azkaban (Book 3),J. K. Rowling,http://images.amazon.com/images/P/0439136350.0...,428,5.852804
1,3,Harry Potter and the Goblet of Fire (Book 4),J. K. Rowling,http://images.amazon.com/images/P/0439139597.0...,387,5.824289
2,5,Harry Potter and the Sorcerer's Stone (Book 1),J. K. Rowling,http://images.amazon.com/images/P/0590353403.0...,278,5.737410
3,9,Harry Potter and the Order of the Phoenix (Boo...,J. K. Rowling,http://images.amazon.com/images/P/043935806X.0...,347,5.501441
4,13,Harry Potter and the Chamber of Secrets (Book 2),J. K. Rowling,http://images.amazon.com/images/P/0439064872.0...,556,5.183453
5,16,The Hobbit : The Enchanting Prelude to The Lor...,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339681.0...,281,5.007117
6,17,The Fellowship of the Ring (The Lord of the Ri...,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339703.0...,368,4.948370
7,26,Harry Potter and the Sorcerer's Stone (Harry P...,J. K. Rowling,http://images.amazon.com/images/P/059035342X.0...,575,4.895652
8,28,"The Two Towers (The Lord of the Rings, Part 2)",J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339711.0...,260,4.880769
9,39,To Kill a Mockingbird,Harper Lee,http://images.amazon.com/images/P/0446310786.0...,510,4.700000
10,47,The Da Vinci Code,Dan Brown,http://images.amazon.com/images/P/0385504209.0...,898,4.642539
11,53,The Five People You Meet in Heaven,Mitch Albom,http://images.amazon.com/images/P/0786868716.0...,430,4.551163
12,55,The Catcher in the Rye,J.D. Salinger,http://images.amazon.com/images/P/0316769487.0...,449,4.545657
13,62,The Lovely Bones: A Novel,Alice Sebold,http://images.amazon.com/images/P/0316666343.0...,1295,4.468726
14,63,1984,George Orwell,http://images.amazon.com/images/P/0451524934.0...,284,4.454225
15,72,Prodigal Summer: A Novel,Barbara Kingsolver,http://images.amazon.com/images/P/0060959037.0...,253,4.450593
16,73,Neverwhere,Neil Gaiman,http://images.amazon.com/images/P/0380789019.0...,265,4.449057
17,78,The Secret Life of Bees,Sue Monk Kidd,http://images.amazon.com/images/P/0142001740.0...,774,4.447028
18,84,Stupid White Men ...and Other Sorry Excuses fo...,Michael Moore,http://images.amazon.com/images/P/0060392452.0...,283,4.356890
19,85,"Tuesdays with Morrie: An Old Man, a Young Man,...",MITCH ALBOM,http://images.amazon.com/images/P/0385484518.0...,493,4.354970
20,88,The Red Tent (Bestselling Backlist),Anita Diamant,http://images.amazon.com/images/P/0312195516.0...,723,4.334716
21,89,The Hitchhiker's Guide to the Galaxy,Douglas Adams,http://images.amazon.com/images/P/0671461494.0...,268,4.328358
22,98,Nickel and Dimed: On (Not) Getting By in America,Barbara Ehrenreich,http://images.amazon.com/images/P/0805063897.0...,335,4.289552
23,100,Into the Wild,Jon Krakauer,http://images.amazon.com/images/P/0385486804.0...,252,4.273810
24,103,Fahrenheit 451,Ray Bradbury,http://images.amazon.com/images/P/3257208626.0...,409,4.264059
25,116,Girl with a Pearl Earring,Tracy Chevalier,http://images.amazon.com/images/P/0452282152.0...,526,4.218631
26,117,Outlander,DIANA GABALDON,http://images.amazon.com/images/P/0440222915.0...,283,4.173145
27,123,Where the Heart Is (Oprah's Book Club (Paperba...,Billie Letts,http://images.amazon.com/images/P/0446672211.0...,585,4.105983
28,124,Seabiscuit: An American Legend,LAURA HILLENBRAND,http://images.amazon.com/images/P/0449005615.0...,275,4.098182
29,126,Life of Pi,Yann Martel,http://images.amazon.com/images/P/0151008116.0...,664,4.088855
30,130,The Bean Trees,Barbara Kingsolver,http://images.amazon.com/images/P/0060915544.0...,389,4.087404
31,133,"A Child Called \It\"": One Child's Courage to S...",Dave Pelzer,http://images.amazon.com/images/P/1558743669.0...,265,4.086792
32,135,ANGELA'S ASHES,Frank McCourt,http://images.amazon.com/images/P/0684874350.0...,279,4.075269
33,137,Good in Bed,Jennifer Weiner,http://images.amazon.com/images/P/0743418174.0...,490,4.055102
34,139,Fast Food Nation: The Dark Side of the All-Ame...,Eric Schlosser,http://images.amazon.com/images/P/0060938455.0...,321,4.037383
35,140,American Gods,Neil Gaiman,http://images.amazon.com/images/P/0380789035.0...,302,4.006623
36,141,Skipping Christmas,JOHN GRISHAM,http://images.amazon.com/images/P/0385505833.0...,322,4.006211
37,147,Left Behind: A Novel of the Earth's Last Days ...,Tim Lahaye,http://images.amazon.com/images/P/0842329129.0...,318,4.003145
38,149,"The Golden Compass (His Dark Materials, Book 1)",PHILIP PULLMAN,http://images.amazon.com/images/P/037582345X.0...,336,4.000000
39,157,The Color Purple,Alice Walker,http://images.amazon.com/images/P/0671617028.0...,314,3.964968
40,163,Silence of the Lambs,Thomas Harris,http://images.amazon.com/images/P/0312924585.0...,256,3.960938
41,166,About a Boy,Nick Hornby,http://images.amazon.com/images/P/1573227331.0...,262,3.900763
42,173,Seven Up (A Stephanie Plum Novel),Janet Evanovich,http://images.amazon.com/images/P/0312265840.0...,278,3.888489
43,175,The Alchemist: A Fable About Following Your Dream,Paulo Coelho,http://images.amazon.com/images/P/0062502174.0...,266,3.875940
44,177,Hard Eight : A Stephanie Plum Novel (A Stephan...,Janet Evanovich,http://images.amazon.com/images/P/0312983867.0...,269,3.825279
45,182,Suzanne's Diary for Nicholas,James Patterson,http://images.amazon.com/images/P/0316969443.0...,457,3.820569
46,186,Lord of the Flies,William Gerald Golding,http://images.amazon.com/images/P/0399501487.0...,259,3.818533
47,192,A Prayer for Owen Meany,John Irving,http://images.amazon.com/images/P/0345361792.0...,413,3.796610
48,194,"The Vampire Lestat (Vampire Chronicles, Book II)",ANNE RICE,http://images.amazon.com/images/P/0345313860.0...,301,3.777409
49,195,White Oleander : A Novel (Oprah's Book Club),Janet Fitch,http://images.amazon.com/images/P/0316284955.0...,356,3.772472

# df6 is my popularity based recommender system

# Creating a collaborative based RS

In [39]:
x= ratings_with_name.groupby('User-ID').count()['Book-Rating'] > 200
padhe_like_users = x[x].index

In [40]:
filtered_rating = ratings_with_name[ratings_with_name['User-ID'].isin(padhe_like_users)]

In [41]:
y = filtered_rating.groupby('Book-Title').count()['Book-Rating'] >= 50
famous_books = y[y].index

In [42]:
final_ratings  = filtered_rating[filtered_rating['Book-Title'].isin(famous_books)]

In [43]:
pt = final_ratings.pivot_table(index='Book-Title', columns='User-ID',values='Book-Rating')

In [44]:
pt.shape

(706, 810)

In [45]:
pt.fillna(0,inplace=True)

In [46]:
from sklearn.metrics.pairwise import cosine_similarity

In [47]:
similarity_score = cosine_similarity(pt)

In [48]:
def recommend(book_name):
    find = np.where(pt.index==book_name)[0][0];
    #distances = similarity_score[find];
    similar = sorted(list(enumerate(similarity_score[find])), key = lambda x:x[1], reverse = True)[1:6];
    for i in similar:
        print(pt.index[i[0]])

In [52]:
recommend('Harry Potter and the Prisoner of Azkaban (Book 3)')

Harry Potter and the Goblet of Fire (Book 4)
Harry Potter and the Chamber of Secrets (Book 2)
Harry Potter and the Order of the Phoenix (Book 5)
Harry Potter and the Sorcerer's Stone (Book 1)
Harry Potter and the Sorcerer's Stone (Harry Potter (Paperback))

# created a collaborative recommender system